### ISSUE TITLE
[Bug] Navigator becomes inactive when exiting through trash/close all button

### ISSUE THREAD

**Issue by 8S3aK8** [w2sv/FileNavigator#46]
### Overview

https://github.com/w2sv/FileNavigator/assets/144175213/9e1d615e-96f2-410f-a5e0-f8a68b285ab5

The app becomes inactive when exited through the "Trash Button/Close All" Button. If possible, please keep the app active when doing so, thanks. 

Also, thank you for the app - I really like it

### How to reproduce

As seen in video,
1. Open and start the navigator
2. Press the three horizontal bars
3. Click the trash/close all button

### Version

0.2.0

### Android Version

Android 14

### Device Model

Tecno LI9

**Comment by 8S3aK8** [comment]
Closing since, found out that this has something more to do with aggressive power savings or memory clean ups with Android 14 more than anything else

**Comment by w2sv** [comment]
Hey, sorry for taking so long to get back to you. 
Thank you for the detailed report comprising even a screen recording, greatly appreciate that. As you already said, however, I fear it's not possible to change that, as it is tied to the basic Android process management. If you clear your memory or use the 'close all' button, you're signalling that you want all active non-system app processes to be terminated and the memory to be freed, which naturally also includes the navigator service. And unfortunately (or not, depending on how you look at it), it's not possible to make an app process immune to that. I already tried to make the navigator persist beyond the app being killed, because I too think they should work independently, enabling the navigator to work despite the app being killed, but AFAIK that's just not possible 🤷
